### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by fdegir**

### CODE REVIEW

**Comment by fdegir** [comment]
@GerMcMahon getting things ready for relaunching the end user council.
Could you please review this pull request?

**Review by GerMcMahon — APPROVED** [review]

**Review by roxannejoncas — COMMENTED** [review]
Bi-monthly could mean twice a month or every other month? I assume you mean twice a month, so I would say "every two weeks." @fdegir @GerMcMahon

**Comment by fdegir** [comment]
> Bi-monthly could mean twice a month or every other month? I assume you mean twice a month, so I would say "every two weeks." @fdegir @GerMcMahon

The meetings will happen every other month in the beginning.

Doesn't bi-weekly mean every other week?

**Comment by fdegir** [comment]
@zestyroxy replaced bi-monthly with every other month.

**Pull request merged**
